name: 'Setup J Language'
description: 'Used to interpret J source. Set up a specific version of the J interpreter.'
author: 'IbzanHyena'
inputs:
  j-version:
    description: 'Optional version to use. If not provided, will default to the latest non-beta version.'
    default: '903'
  addons:
    description: 'Addons to install. If not provided, installs all addons.'
    default: 'all'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/setup.sh 
      shell: bash
      env:
        J_VERSION: ${{ inputs.j-version }}
        J_ADDONS: ${{ inputs.addons }}

